version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_serilog
    ports:
      - "5000:8080"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
